services:
    dm_carousel.configure_menu_listener:
        class: Dm\Bundle\CarouselBundle\EventListener\ConfigureMenuListener
        arguments: ["@security.authorization_checker"]
        tags:
          - { name: kernel.event_listener, event: dm_admin.menu_configure, method: onMenuConfigure }
