dm_content:
    resource: "@DmContentBundle/Controller/"
    type:     annotation
    prefix:   /

dm_attachment:
    resource: "@DmAttachmentBundle/Controller/"
    type:     annotation
    prefix:   /

dm_carousel:
    resource: "@DmCarouselBundle/Controller/"
    type:     annotation
    prefix:   /

dm_security:
    resource: "@DmSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

dm_user:
    resource: "@DmUserBundle/Controller"
    type:     annotation

dm_theme:
    resource: "@DmAdminBundle/Controller"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

login_check:
    path: /admin/login_check

logout:
    path: /admin/logout
