services:
    dm_content.configure_menu_listener:
        class: Dm\Bundle\ContentBundle\EventListener\ConfigureMenuListener
        arguments: ["@security.authorization_checker"]
        tags:
          - { name: kernel.event_listener, event: dm_admin.menu_configure, method: onMenuConfigure }

    textarea_image_util:
        class: Dm\Bundle\ContentBundle\Util\TextareaImageUtil
        arguments: 
            - '%kernel.root_dir%/../web'
            - "@filesystem"
